# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        # keys
        SESSION_SECRET: 'secret'
        AES_KEY: 'key'
        # mariaDB
        DB: 'test'
        DB_HOST: '172.17.0.1'
        DB_PORT: 3306
        DB_USER: 'root'
        DB_PWD: ''
    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test
